import type {
  Activity,
  AiReview,
  Dashboard,
  Email,
  Rfq,
  RfqDetail,
  WorkflowStat,
} from "@workspace/api-zod";

export const rfqs: Rfq[] = [
  {
    id: 1,
    rfqNumber: "RFQ-2026-00125",
    customer: "Alex Morgan",
    customerCompany: "ABC Aviation",
    partNumber: "PT6A-42 FUEL PUMP",
    source: "EMAIL",
    requestType: "NEW_PART_PURCHASE",
    confidence: 97,
    priority: "HIGH",
    status: "UNDER_REVIEW",
    createdAt: "2026-09-08T08:30:00Z",
    age: "Today",
  },
  {
    id: 2,
    rfqNumber: "RFQ-2026-00126",
    customer: "Priya Shah",
    customerCompany: "Global Air Services",
    partNumber: "GASKET KIT 301-771",
    source: "WEBSITE",
    requestType: "PARTS_EXCHANGE",
    confidence: 94,
    priority: "MEDIUM",
    status: "PROCESSING",
    createdAt: "2026-09-08T07:45:00Z",
    age: "Today",
  },
  {
    id: 3,
    rfqNumber: "RFQ-2026-00127",
    customer: "Daniel Reyes",
    customerCompany: "SkyTech Aviation",
    partNumber: "PW127M STARTER",
    source: "EMAIL",
    requestType: "REPAIR",
    confidence: 68,
    priority: "HIGH",
    status: "NEEDS_HUMAN_REVIEW",
    createdAt: "2026-09-07T16:20:00Z",
    age: "Yesterday",
  },
  {
    id: 4,
    rfqNumber: "RFQ-2026-00124",
    customer: "Maya Chen",
    customerCompany: "AeroParts International",
    partNumber: "HYDRAULIC VALVE 500-112",
    source: "PORTAL",
    requestType: "OVERHAUL",
    confidence: 88,
    priority: "URGENT",
    status: "ANALYZING",
    createdAt: "2026-09-07T14:05:00Z",
    age: "Yesterday",
  },
  {
    id: 5,
    rfqNumber: "RFQ-2026-00123",
    customer: "Thomas Becker",
    customerCompany: "NorthStar Regional",
    partNumber: "LIFE VEST P/N 1174",
    source: "PHONE",
    requestType: "INSPECTION",
    confidence: 91,
    priority: "LOW",
    status: "COMPLETED",
    createdAt: "2026-09-06T11:40:00Z",
    age: "2 days ago",
  },
  {
    id: 6,
    rfqNumber: "RFQ-2026-00122",
    customer: "Olivia Grant",
    customerCompany: "Meridian Charter",
    partNumber: "VHF TRANSCEIVER 822-101",
    source: "EMAIL",
    requestType: "NEW_PART_PURCHASE",
    confidence: 99,
    priority: "MEDIUM",
    status: "NEW",
    createdAt: "2026-09-06T09:15:00Z",
    age: "2 days ago",
  },
];

export const rfqDetails: RfqDetail[] = rfqs.map((rfq, index) => ({
  ...rfq,
  description: `Customer request for ${rfq.partNumber.toLowerCase()} support, including lead time and serviceability options.`,
  quantity: index === 0 ? 2 : index === 2 ? 1 : 4,
  aircraft: index % 2 === 0 ? "Beechcraft King Air 350" : "ATR 72-600",
  notes:
    index === 2
      ? "Confirm whether customer requires teardown report with repair return."
      : "Customer requested trace documentation and standard warranty terms.",
  emailSubject: `Request for ${rfq.partNumber}`,
  sender: `${rfq.customer} <${rfq.customer.toLowerCase().replace(" ", ".")}@${rfq.customerCompany.toLowerCase().replaceAll(" ", "")}.com>`,
}));

export const emails: Email[] = [
  {
    id: 1,
    sender: "ABC Aviation",
    senderEmail: "alex.morgan@abcaviation.com",
    subject: "Request for PT6A Fuel Pump",
    receivedAt: "Today, 10:30 AM",
    aiStatus: "ANALYZED",
    requestType: "NEW_PART_PURCHASE",
    confidence: 97,
    status: "RFQ_CREATED",
  },
  {
    id: 2,
    sender: "SkyTech Aviation",
    senderEmail: "daniel.reyes@skytech.aero",
    subject: "PW127M Starter Repair Capability",
    receivedAt: "Yesterday, 4:20 PM",
    aiStatus: "ANALYZED",
    requestType: "REPAIR",
    confidence: 68,
    status: "PENDING_REVIEW",
  },
  {
    id: 3,
    sender: "AeroParts International",
    senderEmail: "procurement@aeroparts-intl.com",
    subject: "Hydraulic Valve Overhaul Request",
    receivedAt: "Yesterday, 2:05 PM",
    aiStatus: "PROCESSING",
    requestType: "OVERHAUL",
    confidence: 88,
    status: "RFQ_CREATED",
  },
  {
    id: 4,
    sender: "Meridian Charter",
    senderEmail: "ops@meridiancharter.com",
    subject: "VHF Transceiver Availability",
    receivedAt: "2 days ago",
    aiStatus: "ANALYZED",
    requestType: "NEW_PART_PURCHASE",
    confidence: 99,
    status: "RFQ_CREATED",
  },
];

export const aiReviews: AiReview[] = [
  {
    id: 1,
    rfqId: 3,
    rfqNumber: "RFQ-2026-00127",
    customer: "SkyTech Aviation",
    classification: "REPAIR",
    confidence: 68,
    reason: "Low AI confidence",
    status: "NEEDS_REVIEW",
  },
  {
    id: 2,
    rfqId: 4,
    rfqNumber: "RFQ-2026-00124",
    customer: "AeroParts International",
    classification: "OVERHAUL",
    confidence: 88,
    reason: "Missing serviceability information",
    status: "NEEDS_REVIEW",
  },
];

const workflows: WorkflowStat[] = [
  { name: "Parts Exchange", active: 8, total: 12, progress: 67, tone: "blue" },
  { name: "New Part Purchase", active: 14, total: 20, progress: 70, tone: "teal" },
  { name: "Repair", active: 6, total: 10, progress: 60, tone: "amber" },
  { name: "Overhaul", active: 4, total: 7, progress: 57, tone: "violet" },
];

const activities: Activity[] = [
  { id: 1, type: "email", title: "New Email Received", description: "Request for PT6A Fuel Pump from ABC Aviation", time: "10 minutes ago", tone: "blue" },
  { id: 2, type: "ai", title: "AI Classified RFQ", description: "RFQ-2026-00125 classified as New Part Purchase", time: "12 minutes ago", tone: "violet" },
  { id: 3, type: "rfq", title: "RFQ Created", description: "RFQ-2026-00126 added to the processing queue", time: "1 hour ago", tone: "green" },
  { id: 4, type: "compliance", title: "Compliance Approved", description: "RFQ-2026-00123 cleared for quote preparation", time: "2 hours ago", tone: "amber" },
  { id: 5, type: "quote", title: "Quote Generated", description: "Quote draft prepared for Meridian Charter", time: "3 hours ago", tone: "slate" },
];

export const dashboard: Dashboard = {
  metrics: [
    { label: "New RFQs", value: 24, trend: 12, tone: "blue" },
    { label: "Emails Waiting", value: 12, trend: 8, tone: "amber" },
    { label: "AI Review Required", value: 5, trend: -4, tone: "violet" },
    { label: "Quotes Pending", value: 8, trend: 16, tone: "orange" },
    { label: "Quotes Sent", value: 31, trend: 11, tone: "green" },
    { label: "Accepted Orders", value: 14, trend: 6, tone: "teal" },
    { label: "Orders in Fulfillment", value: 9, trend: 3, tone: "slate" },
  ],
  recentRfqs: rfqs.slice(0, 5),
  workflows,
  activities,
};